name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test-macos:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Tuist via mise
        run: |
          mise install

      - name: Generate Xcode project
        run: |
          mise exec -- tuist generate

      - name: Build and test macOS
        run: |
          xcodebuild test \
            -workspace macmo.xcworkspace \
            -scheme macmo \
            -destination 'platform=macOS' \
            -only-testing:macmoTests \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

  build-and-test-ios:
    runs-on: macos-15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Tuist via mise
        run: |
          mise install

      - name: Generate Xcode project
        run: |
          mise exec -- tuist generate

      - name: Build and test iOS
        run: |
          DEVICE=$(xcrun simctl list devices available iPhone | grep -E "iPhone.*\(" | head -n 1 | sed -E 's/.*\(([A-F0-9-]+)\).*/\1/')
          echo "Using simulator ID: $DEVICE"
          xcodebuild test \
            -workspace macmo.xcworkspace \
            -scheme macmo \
            -destination "platform=iOS Simulator,id=$DEVICE" \
            -only-testing:macmoiOSTests \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
